champions = {
    "Ahri": ["Star Guardian", "Sorcerer"],
    "Annie": ["Mech-Pilot", "Sorcerer"],
    "Ashe": ["Celestial", "Sniper"],
    "Aurelion Sol": ["Rebel", "Starship"],
    "Bard": ["Astro", "Mystic"],
    "Blitzcrank": ["Chrono", "Brawler"],
    "Caitlyn": ["Chrono", "Sniper"],
    "Cassiopeia": ["Battlecast", "Mystic"],
    "Darius": ["Space Pirate", "Mana-Reaver"],
    "Ekko": ["Cybernetic", "Infiltrator"],
    "Ezreal": ["Chrono", "Blaster"],
    "Fiora": ["Cybernetic", "Blademaster"],
    "Fizz": ["Mech-Pilot", "Infiltrator"],
    "Gangplank": ["Space Pirate", "Mercenary", "Demolitionist"],
    "Gnar": ["Astro", "Brawler"],
    "Graves": ["Space Pirate", "Blaster"],
    "Illaoi": ["Battlecast", "Brawler"],
    "Irelia": ["Cybernetic", "Mana-Reaver", "Blademaster"],
    "Janna": ["Star Guardian", "Paragon"],
    "Jarvan IV": ["Dark Star", "Protector"],
    "Jayce": ["Space Pirate", "Vanguard"],
    "Jhin": ["Dark Star", "Sniper"],
    "Jinx": ["Rebel", "Blaster"],
    "Karma": ["Dark Star", "Mystic"],
    "Kog'Maw": ["Battlecast", "Blaster"],
    "Leona": ["Cybernetic", "Vanguard"],
    "Lucian": ["Cybernetic", "Blaster"],
    "Lulu": ["Celestial", "Mystic"],
    "Malphite": ["Rebel", "Brawler"],
    "Master Yi": ["Rebel", "Blademaster"],
    "Mordekaiser": ["Dark Star", "Vanguard"],
    "Nautilus": ["Astro", "Vanguard"],
    "Neeko": ["Star Guardian", "Protector"],
    "Nocturne": ["Battlecast", "Infiltrator"],
    "Poppy": ["Star Guardian", "Vanguard"],
    "Rakan": ["Celestial", "Protector"],
    "Riven": ["Chrono", "Blademaster"],
    "Rumble": ["Mech-Pilot", "Demolitionist"],
    "Shaco": ["Dark Star", "Infiltrator"],
    "Shen": ["Chrono", "Blademaster"],
    "Soraka": ["Star Guardian", "Mystic"],
    "Syndra": ["Star Guardian", "Sorcerer"],
    "Teemo": ["Astro", "Sniper"],
    "Thresh": ["Chrono", "Mana-Reaver"],
    "Twisted Fate": ["Chrono", "Sorcerer"],
    "Urgot": ["Battlecast", "Protector"],
    "Vayne": ["Cybernetic", "Sniper"],
    "Vi": ["Cybernetic", "Brawler"],
    "Viktor": ["Battlecast", "Sorcerer"],
    "Wukong": ["Chrono", "Vanguard"],
    "Xayah": ["Celestial", "Blademaster"],
    "Xerath": ["Dark Star", "Sorcerer"],
    "Xin Zhao": ["Celestial", "Protector"],
    "Yasuo": ["Rebel", "Blademaster"],
    "Zed": ["Rebel", "Infiltrator"],
    "Ziggs": ["Rebel", "Demolitionist"],
    "Zoe": ["Star Guardian", "Sorcerer"]
}

champions_size = len(champions)
